# Generated by Django 4.2.1 on 2023-05-21 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_alter_categoria_options_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('nome',), 'verbose_name_plural': 'Itens'},
        ),
    ]
